export interface CustomsPortCode {
  sno: number;
  state: string;
  zone: string;
  type: string;
  name: string;
  portCode: string;
  edi: string;
  status: string;
}

export const portCodesData: CustomsPortCode[] = [
  { sno: 1, state: "Andaman and Nicobar Islands", zone: "Kolkata", type: "Port", name: "Port Blair", portCode: "INIXZ1", edi: "YES", status: "EDI enabled" },
  { sno: 2, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "Port", name: "Gangavaram Port, Andhra Pradesh", portCode: "INGGV1", edi: "YES", status: "EDI enabled" },
  { sno: 3, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "ICD", name: "Icd Marripalam, District - Guntur, A.P.", portCode: "INGNR6", edi: "YES", status: "EDI enabled" },
  { sno: 4, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "Port", name: "Custom House Port Area Kakinada 533007", portCode: "INKAK1", edi: "YES", status: "EDI enabled" },
  { sno: 5, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "Port", name: "Ices Krishnapatnam Port, Nellore-524003", portCode: "INKRI1", edi: "YES", status: "EDI enabled" },
  { sno: 6, state: "Andhra Pradesh", zone: "Hyderabad", type: "ICD", name: "Icd Thimmapur, 11-60/5-7 Thimmapur 509325 Ap", portCode: "INTMX6", edi: "YES", status: "EDI enabled" },
  { sno: 7, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "Port", name: "Custom House Port Area Viskhapatnam 530035", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 8, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "ACC", name: "Air Cargo Complex Visakhapatnam", portCode: "INVTZ4", edi: "YES", status: "EDI enabled" },
  { sno: 9, state: "Assam", zone: "GUWAHATI", type: "ICD", name: "Concor, Icd Amingaon, Guwahati- 781031", portCode: "INAMG6", edi: "YES", status: "EDI enabled" },
  { sno: 10, state: "Assam", zone: "GUWAHATI", type: "ACC", name: "Guwahati Air Cargo", portCode: "INGAU4", edi: "YES", status: "EDI enabled" },
  { sno: 11, state: "Bihar", zone: "Patna", type: "LCS", name: "Bairgania", portCode: "INBGUB", edi: "YES", status: "EDI enabled" },
  { sno: 12, state: "Bihar", zone: "Patna", type: "LCS", name: "Bhimnagar", portCode: "INBNRB", edi: "YES", status: "EDI enabled" },
  { sno: 13, state: "Bihar", zone: "Patna", type: "LCS", name: "Bhitamore", portCode: "INBTMB", edi: "YES", status: "EDI enabled" },
  { sno: 14, state: "Bihar", zone: "Patna", type: "LCS", name: "Galgalia", portCode: "INGALB", edi: "YES", status: "EDI enabled" },
  { sno: 15, state: "Bihar", zone: "Patna", type: "LCS", name: "Jayanagar", portCode: "INJAYB", edi: "YES", status: "EDI enabled" },
  { sno: 16, state: "Bihar", zone: "Patna", type: "LCS", name: "Lcs Jogbani, Dist:Araria, Bihar", portCode: "INJBNB", edi: "YES", status: "EDI enabled" },
  { sno: 17, state: "Bihar", zone: "Patna", type: "LCS", name: "Pipraun", portCode: "INKJIB", edi: "YES", status: "EDI enabled" },
  { sno: 18, state: "Bihar", zone: "Patna", type: "LCS", name: "Kunauli", portCode: "INKNLB", edi: "YES", status: "EDI enabled" },
  { sno: 19, state: "Bihar", zone: "Patna", type: "LCS", name: "Laukaha", portCode: "INLKQB", edi: "YES", status: "EDI enabled" },
  { sno: 20, state: "Bihar", zone: "Patna", type: "LCS", name: "Lcs Raxaul, Dist: East Champaran, Bihar", portCode: "INRXLB", edi: "YES", status: "EDI enabled" },
  { sno: 21, state: "Bihar", zone: "Patna", type: "LCS", name: "Sonabarsa", portCode: "INSNBB", edi: "YES", status: "EDI enabled" },
  { sno: 22, state: "Chhattisgarh", zone: "Bhopal", type: "ICD", name: "Icd Raipur, Nr Goods Shed Kapa Raipur 492009", portCode: "INRAI6", edi: "YES", status: "EDI enabled" },
  { sno: 23, state: "Chhattisgarh", zone: "Bhopal", type: "ICD", name: "Icd- Naya Raipur", portCode: "INRML6", edi: "YES", status: "EDI enabled" },
  { sno: 24, state: "Delhi", zone: "Delhi", type: "ACC", name: "New Custom House, Nr Igi Airport New Delhi 110037", portCode: "INDEL4", edi: "YES", status: "EDI enabled" },
  { sno: 25, state: "Delhi", zone: "Delhi", type: "ICD", name: "Icd Patparganj, Gazipur, Nr Gazipur Bus Depot, Nd", portCode: "INPPG6", edi: "YES", status: "EDI enabled" },
  { sno: 26, state: "Delhi", zone: "Delhi", type: "ICD", name: "Icd Tughlakabad New Delhi 110020", portCode: "INTKD6", edi: "YES", status: "EDI enabled" },
  { sno: 27, state: "Goa", zone: "Pune", type: "ACC", name: "Goa Air Cargo Complex, Sada Complex , Marmagoa", portCode: "INGOI4", edi: "YES", status: "EDI enabled" },
  { sno: 28, state: "Goa", zone: "Pune", type: "ICD", name: "Icd Verna", portCode: "INMDG6", edi: "YES", status: "EDI enabled" },
  { sno: 29, state: "Goa", zone: "Pune", type: "Port", name: "New Custom House Marmagoa, Goa Pin 403803", portCode: "INMRM1", edi: "YES", status: "EDI enabled" },
  { sno: 30, state: "Goa", zone: "Pune", type: "Port", name: "Panaji Port", portCode: "INPAN1", edi: "YES", status: "EDI enabled" },
  { sno: 31, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Ankleshwar Opp Ongc Tnship Old Nh8 Ankleshwar", portCode: "INAKV6", edi: "YES", status: "EDI enabled" },
  { sno: 32, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Alang Port", portCode: "INALA1", edi: "YES", status: "EDI enabled" },
  { sno: 33, state: "Gujarat", zone: "Ahmedabad", type: "ACC", name: "Acc Ahmedabad, Old Airport Sahibaug Ahmedabad 12", portCode: "INAMD4", edi: "YES", status: "EDI enabled" },
  { sno: 34, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Bedi Port Jamnagar, Gujarat", portCode: "INBED1", edi: "YES", status: "EDI enabled" },
  { sno: 35, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Bhavnagar Sea", portCode: "INBHU1", edi: "YES", status: "EDI enabled" },
  { sno: 36, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Dashrath Vadodara Gujarat 391740", portCode: "INBRC6", edi: "YES", status: "EDI enabled" },
  { sno: 37, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Dahej Port Custom House Dist: Baroach Gujarat", portCode: "INDAH1", edi: "YES", status: "EDI enabled" },
  { sno: 38, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Shb Icd Surat", portCode: "INHIR6", edi: "YES", status: "EDI enabled" },
  { sno: 39, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Hazira Port, Choryashi, Bypass Rd., Hazira, Surat", portCode: "INHZA1", edi: "YES", status: "EDI enabled" },
  { sno: 40, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Custom House , Near Balaji Temple Kandla 370210", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 41, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Jakhau Port", portCode: "INJAK1", edi: "YES", status: "EDI enabled" },
  { sno: 42, state: "Gujarat", zone: "Ahmedabad", type: "ACC", name: "Jamnagar Air Cargo", portCode: "INJGA4", edi: "YES", status: "EDI enabled" },
  { sno: 43, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Sachana", portCode: "INJKA6", edi: "YES", status: "EDI enabled" },
  { sno: 44, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Kribhco Infstr Ltd,Hazira,Kribhco Ngr,Surat,Gujrat", portCode: "INKBC6", edi: "YES", status: "EDI enabled" },
  { sno: 45, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Kodinar Port (Muldwarka)", portCode: "INKDN1", edi: "YES", status: "EDI enabled" },
  { sno: 46, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Magdalla Port Urmi Complex Sangrampura Surat 2", portCode: "INMDA1", edi: "YES", status: "EDI enabled" },
  { sno: 47, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Mundra Port Sez Mundra Gujarat", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 48, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Navlakhi Port", portCode: "INNAV1", edi: "YES", status: "EDI enabled" },
  { sno: 49, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Okha Port", portCode: "INOKH1", edi: "YES", status: "EDI enabled" },
  { sno: 50, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Old Mundra Port", portCode: "INOMU1", edi: "YES", status: "EDI enabled" },
  { sno: 51, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Pipavav Port P:Ucchaiya D: Amreli Gujarat 365560", portCode: "INPAV1", edi: "YES", status: "EDI enabled" },
  { sno: 52, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Porbandar Port", portCode: "INPBD1", edi: "YES", status: "EDI enabled" },
  { sno: 53, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Surat Diamond Park,Gidc,Sachin,Surat 394230", portCode: "INSAC6", edi: "YES", status: "EDI enabled" },
  { sno: 54, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Thar Dry Port, Kadi Road Sanand Ahmedabad", portCode: "INSAU6", edi: "YES", status: "EDI enabled" },
  { sno: 55, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Sabarmati, Kaligam Sabarmati Ahmedabad 382470", portCode: "INSBI6", edi: "YES", status: "EDI enabled" },
  { sno: 56, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Sikka Port", portCode: "INSIK1", edi: "YES", status: "EDI enabled" },
  { sno: 57, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Tuna Port", portCode: "INTUN1", edi: "YES", status: "EDI enabled" },
  { sno: 58, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Vadinar", portCode: "INVAD1", edi: "YES", status: "EDI enabled" },
  { sno: 59, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Valvada, Nh 8 Taluka Umbergaon Valsad Gujarat", portCode: "INVPI6", edi: "YES", status: "EDI enabled" },
  { sno: 60, state: "Gujarat", zone: "Ahmedabad", type: "Port", name: "Sea Port-Salaya, Gujarat", portCode: "INSAL1", edi: "YES", status: "EDI enabled" },
  { sno: 61, state: "Gujarat", zone: "Ahmedabad", type: "ICD", name: "Icd Viramgam, Village-Bhojwa, Taluk Viramgam, District- Ahmedabad, Gujarat", portCode: "INVGR6", edi: "YES", status: "EDI enabled" },
  { sno: 62, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd, Bawal, Rewari, Haryana", portCode: "INBAW6", edi: "YES", status: "EDI enabled" },
  { sno: 63, state: "Haryana", zone: "Delhi", type: "ICD", name: "Panchi Gujaran,Tehsil-Gannaur-Sonepat Dist. Hr", portCode: "INBDM6", edi: "YES", status: "EDI enabled" },
  { sno: 64, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Grfl, Village Piyala, Faridabad", portCode: "INBFR6", edi: "YES", status: "EDI enabled" },
  { sno: 65, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Concor, Sector 25, Faridabad", portCode: "INBVC6", edi: "YES", status: "EDI enabled" },
  { sno: 66, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd, Jattipur, Sonepat", portCode: "INDWN6", edi: "YES", status: "EDI enabled" },
  { sno: 67, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Ballabgarh Sector 59 Faridabad-121004", portCode: "INFBD6", edi: "YES", status: "EDI enabled" },
  { sno: 68, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Garhi Harsaru Sri Maruthi Nagar Gurgaon", portCode: "INGHR6", edi: "YES", status: "EDI enabled" },
  { sno: 69, state: "Haryana", zone: "Delhi", type: "ICD", name: "Kribhco Logistic Park,Rewari, Haryana", portCode: "INPKR6", edi: "YES", status: "EDI enabled" },
  { sno: 70, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Panipat Babarpur Railway Station Panipat", portCode: "INPNP6", edi: "YES", status: "EDI enabled" },
  { sno: 71, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Patli, Gurgaon, Haryana", portCode: "INPTL6", edi: "YES", status: "EDI enabled" },
  { sno: 72, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Palwal", portCode: "INPWL6", edi: "YES", status: "EDI enabled" },
  { sno: 73, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Rewari, Rewari Haryana", portCode: "INREA6", edi: "YES", status: "EDI enabled" },
  { sno: 74, state: "Haryana", zone: "Delhi", type: "ICD", name: "Icd Barhi, Ganaur, Distt-Sonepat, Haryana", portCode: "INRUG6", edi: "YES", status: "EDI enabled" },
  { sno: 75, state: "Himachal Pradesh", zone: "Delhi(P)", type: "ICD", name: "Icd Baddi", portCode: "INBDI6", edi: "YES", status: "EDI enabled" },
  { sno: 76, state: "Jammu and Kashmir", zone: "Delhi(P)", type: "ACC", name: "Srinagar", portCode: "INSXR4", edi: "YES", status: "EDI enabled" },
  { sno: 77, state: "Jharkhand", zone: "Patna", type: "ICD", name: "Icd Jamshedpur,Near Fci Godown,Tatanagar,Jharkhand", portCode: "INIXW6", edi: "YES", status: "EDI enabled" },
  { sno: 78, state: "Karnataka", zone: "Bengaluru", type: "ACC", name: "Acc Bangalore, Bengaluru International Airport", portCode: "INBLR4", edi: "YES", status: "EDI enabled" },
  { sno: 79, state: "Karnataka", zone: "Bengaluru", type: "ICD", name: "Icd, Hassan, Karnataka", portCode: "INHAS6", edi: "YES", status: "EDI enabled" },
  { sno: 80, state: "Karnataka", zone: "Bengaluru", type: "Port", name: "Mangalore (Old)", portCode: "INIXE1", edi: "YES", status: "EDI enabled" },
  { sno: 81, state: "Karnataka", zone: "Bengaluru", type: "ACC", name: "Mangalore Air Cargo", portCode: "INIXE4", edi: "YES", status: "EDI enabled" },
  { sno: 82, state: "Karnataka", zone: "Bengaluru", type: "Port", name: "Karwar (Including Sardeshivagad)", portCode: "INKRW1", edi: "YES", status: "EDI enabled" },
  { sno: 83, state: "Karnataka", zone: "Bengaluru", type: "Port", name: "New Custom House Panambur Mangalore 575010", portCode: "INNML1", edi: "YES", status: "EDI enabled" },
  { sno: 84, state: "Karnataka", zone: "Bengaluru", type: "ICD", name: "Icd White Field Plantations, Hoskote, Bangalore", portCode: "INWFD6", edi: "YES", status: "EDI enabled" },
  { sno: 85, state: "Karnataka", zone: "Bengaluru", type: "ICD", name: "Icd Desur", portCode: "INDRU6", edi: "YES", status: "EDI enabled" },
  { sno: 86, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "Port", name: "Azhikkal Port", portCode: "INAZK1", edi: "YES", status: "EDI enabled" },
  { sno: 87, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "Port", name: "Customs House, Beypore", portCode: "INBEY1", edi: "YES", status: "EDI enabled" },
  { sno: 88, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "ACC", name: "Acc Kozhikode, Karipur Kerala 673647", portCode: "INCCJ4", edi: "YES", status: "EDI enabled" },
  { sno: 89, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "Port", name: "Cochin Custom House Wellingdon Island Cochin682009", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 90, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "ACC", name: "Kochi Airport Nedumbassery Cochin Kerala 683111", portCode: "INCOK4", edi: "YES", status: "EDI enabled" },
  { sno: 91, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "Port", name: "Pallithottam P.O, Kollam, Kerala 691006", portCode: "INKUK1", edi: "YES", status: "EDI enabled" },
  { sno: 92, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "ICD", name: "Icd Kottayam, Village: Nattakam, Kottayam - Kerala", portCode: "INKYM6", edi: "YES", status: "EDI enabled" },
  { sno: 93, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "ICD", name: "Icd Mathilakam, Thrissur Dist, Kerala", portCode: "INTCR6", edi: "YES", status: "EDI enabled" },
  { sno: 94, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "ACC", name: "Acc Shanghumugham Thiruvananthapuram Kerala", portCode: "INTRV4", edi: "YES", status: "EDI enabled" },
  { sno: 95, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "Port", name: "Vizhinjam Port", portCode: "INVZJ1", edi: "YES", status: "EDI enabled" },
  { sno: 96, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "M/S Pegasus Icd, Vill-Dhannad, Indore, Mp 453001", portCode: "INDHA6", edi: "YES", status: "EDI enabled" },
  { sno: 97, state: "Madhya Pradesh", zone: "Bhopal", type: "ACC", name: "Acc, Devi Ahilyabai Holkar Airport Indore Mp", portCode: "INIDR4", edi: "YES", status: "EDI enabled" },
  { sno: 98, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Icd 113 Concor Complex Sector Iii Pithampur Dhar", portCode: "ININD6", edi: "YES", status: "EDI enabled" },
  { sno: 99, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Icd, Kheda, M.P", portCode: "INKHD6", edi: "YES", status: "EDI enabled" },
  { sno: 100, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Icd Mandideep 34-A1 Nia Dist:Raisen Mp 462046", portCode: "INMDD6", edi: "YES", status: "EDI enabled" },
  { sno: 101, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Icd, Malanpur, Concor, M.P.", portCode: "INMPR6", edi: "YES", status: "EDI enabled" },
  { sno: 102, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Icd, Pawarkheda, Hoshangabad, Mp", portCode: "INPRK6", edi: "YES", status: "EDI enabled" },
  { sno: 103, state: "Madhya Pradesh", zone: "Bhopal", type: "ICD", name: "Concor Icd,Nr Loco Shed,Jaora Rd.,Ratlam(Mp)457001", portCode: "INRTM6", edi: "YES", status: "EDI enabled" },
  { sno: 104, state: "Maharashtra", zone: "Pune", type: "Port", name: "Bankot", portCode: "INBKT1", edi: "YES", status: "EDI enabled" },
  { sno: 105, state: "Maharashtra", zone: "Mumbai, Zone III", type: "ICD", name: "Icd Tarapur, Mahagaon, Tarapur, Thane, Maharashtra", portCode: "INBNG6", edi: "YES", status: "EDI enabled" },
  { sno: 106, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Borkhedi", portCode: "INBOK6", edi: "YES", status: "EDI enabled" },
  { sno: 107, state: "Maharashtra", zone: "Mumbai, Zone I", type: "Port", name: "New Custom House, Ballard Estate Mumbai 400038", portCode: "INBOM1", edi: "YES", status: "EDI enabled" },
  { sno: 108, state: "Maharashtra", zone: "Mumbai, Zone III", type: "ACC", name: "Air Cargo Complex Sahar Andheri(E) Mumbai 400099", portCode: "INBOM4", edi: "YES", status: "EDI enabled" },
  { sno: 109, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Concor Bhusawal, B/H Sayaji Hotel Bhusawal", portCode: "INBSL6", edi: "YES", status: "EDI enabled" },
  { sno: 110, state: "Maharashtra", zone: "Pune", type: "ICD", name: "Icd Concor, Rly Goods Shed Chinchwad Pune 411019", portCode: "INCCH6", edi: "YES", status: "EDI enabled" },
  { sno: 111, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Wardha", portCode: "INCHJ6", edi: "YES", status: "EDI enabled" },
  { sno: 112, state: "Maharashtra", zone: "Pune", type: "Port", name: "Dabhol Port", portCode: "INDHP1", edi: "YES", status: "EDI enabled" },
  { sno: 113, state: "Maharashtra", zone: "Mumbai, Zone III", type: "Port", name: "Dhahanu Port", portCode: "INDHU1", edi: "YES", status: "EDI enabled" },
  { sno: 114, state: "Maharashtra", zone: "Mumbai, Zone III", type: "Port", name: "Digih Sea", portCode: "INDIG1", edi: "YES", status: "EDI enabled" },
  { sno: 115, state: "Maharashtra", zone: "Pune", type: "ICD", name: "Icd Dighi Talera Nagar Pune-Alandi Road Dighi Pune", portCode: "INDIG6", edi: "YES", status: "EDI enabled" },
  { sno: 116, state: "Maharashtra", zone: "Mumbai, Zone III", type: "Port", name: "Port Dharamtar", portCode: "INDMT1", edi: "YES", status: "EDI enabled" },
  { sno: 117, state: "Maharashtra", zone: "Mumbai, Zone III", type: "ACC", name: "Pcccc,Bandra Kurla Complex,Bandra(E),Mumbai,400051", portCode: "INDPC4", edi: "YES", status: "EDI enabled" },
  { sno: 118, state: "Maharashtra", zone: "Pune", type: "ICD", name: "Icd Bhamboli, Pune", portCode: "INGRW6", edi: "YES", status: "EDI enabled" },
  { sno: 119, state: "Maharashtra", zone: "Pune", type: "Port", name: "Port Jaigarh, Sakhar Mohalla, Maharashtra", portCode: "INJGD1", edi: "YES", status: "EDI enabled" },
  { sno: 120, state: "Maharashtra", zone: "Nagpur", type: "ACC", name: "Acc Janori, Janori Dindori, Dist Nasik, Pin 422207", portCode: "INJNR4", edi: "YES", status: "EDI enabled" },
  { sno: 121, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Janori, Janori Dindori Dist: Nasik Pin 422207", portCode: "INJNR6", edi: "YES", status: "EDI enabled" },
  { sno: 122, state: "Maharashtra", zone: "Pune", type: "Port", name: "Kelshi Port", portCode: "INKSH1", edi: "YES", status: "EDI enabled" },
  { sno: 123, state: "Maharashtra", zone: "Mumbai, Zone I", type: "ICD", name: "Icd Mulund Mumbai Maharashtra", portCode: "INMUL6", edi: "YES", status: "EDI enabled" },
  { sno: 124, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Maliwada Daulatabad Aurangabad - 431003", portCode: "INMWA6", edi: "YES", status: "EDI enabled" },
  { sno: 125, state: "Maharashtra", zone: "Nagpur", type: "ACC", name: "Nagpur Air Cargo", portCode: "INNAG4", edi: "YES", status: "EDI enabled" },
  { sno: 126, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Butibori", portCode: "INNGB6", edi: "YES", status: "EDI enabled" },
  { sno: 127, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd (Ajni) Nagpur, Nr Narendra Nagar Nagpur 440027", portCode: "INNGP6", edi: "YES", status: "EDI enabled" },
  { sno: 128, state: "Maharashtra", zone: "Mumbai, Zone II", type: "Port", name: "Jnch, Nhava Sheva Taluka:Uran Dist:Raigard 400707", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 129, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Nasik, Maharashtra", portCode: "INNSK6", edi: "YES", status: "EDI enabled" },
  { sno: 130, state: "Maharashtra", zone: "Pune", type: "ICD", name: "F-Ii Block, Yeshwant Nagar, Pimpri, Pune 400018", portCode: "INPMP6", edi: "YES", status: "EDI enabled" },
  { sno: 131, state: "Maharashtra", zone: "Pune", type: "ACC", name: "Pune Acc", portCode: "INPNQ4", edi: "YES", status: "EDI enabled" },
  { sno: 132, state: "Maharashtra", zone: "Pune", type: "Port", name: "Redi Port, Maharashtra", portCode: "INRED1", edi: "YES", status: "EDI enabled" },
  { sno: 133, state: "Maharashtra", zone: "Pune", type: "Port", name: "Ranpar Port", portCode: "INRNR1", edi: "YES", status: "EDI enabled" },
  { sno: 134, state: "Maharashtra", zone: "Mumbai, Zone III", type: "Port", name: "Revdanda Sea", portCode: "INRVD1", edi: "YES", status: "EDI enabled" },
  { sno: 135, state: "Maharashtra", zone: "Ahmedabad", type: "ICD", name: "Icd, Umbergaon, Maharashtra (Navkar Corp)", portCode: "INSAJ6", edi: "YES", status: "EDI enabled" },
  { sno: 136, state: "Maharashtra", zone: "Pune", type: "ICD", name: "Icd Talegaon A-18 & 18/1 Midc Talegaon Pune 410502", portCode: "INTLG6", edi: "YES", status: "EDI enabled" },
  { sno: 137, state: "Maharashtra", zone: "Pune", type: "Port", name: "Vijaydurg", portCode: "INVYD1", edi: "YES", status: "EDI enabled" },
  { sno: 138, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Icd Waluj, H-22 Midc Waluj Aurangabad", portCode: "INWAL6", edi: "YES", status: "EDI enabled" },
  { sno: 139, state: "Maharashtra", zone: "Nagpur", type: "ICD", name: "Concor Icd, Mihan, Nagpur", portCode: "INKPK6", edi: "YES", status: "EDI enabled" },
  { sno: 140, state: "Assam", zone: "GUWAHATI", type: "LCS", name: "Darranga", portCode: "INDRGB", edi: "YES", status: "EDI enabled" },
  { sno: 141, state: "Assam", zone: "GUWAHATI", type: "LCS", name: "Karimganj Steamerghat", portCode: "INKGJ1", edi: "YES", status: "EDI enabled" },
  { sno: 142, state: "Assam", zone: "GUWAHATI", type: "LCS", name: "Kamardwisa (Rangapani)", portCode: "INPBLB", edi: "YES", status: "EDI enabled" },
  { sno: 143, state: "Manipur", zone: "GUWAHATI", type: "LCS", name: "Moreh", portCode: "INMREB", edi: "YES", status: "EDI enabled" },
  { sno: 144, state: "Tripura", zone: "GUWAHATI", type: "LCS", name: "Agartala", portCode: "INAGTB", edi: "YES", status: "EDI enabled" },
  { sno: 145, state: "Tripura", zone: "GUWAHATI", type: "LCS", name: "Muhurighat", portCode: "INMHGB", edi: "YES", status: "EDI enabled" },
  { sno: 146, state: "Tripura", zone: "GUWAHATI", type: "LCS", name: "Srimantapur", portCode: "INSMPB", edi: "YES", status: "EDI enabled" },
  { sno: 147, state: "Odisha", zone: "Bhubaneswar", type: "ACC", name: "Bhubaneswar", portCode: "INBBI4", edi: "YES", status: "EDI enabled" },
  { sno: 148, state: "Odisha", zone: "Bhubaneswar", type: "ICD", name: "Balasore Icd", portCode: "INBLE6", edi: "YES", status: "EDI enabled" },
  { sno: 149, state: "Odisha", zone: "Bhubaneswar", type: "Port", name: "Dhamra Port, Dosinga, Bhadrakh, Odisha, 756171", portCode: "INDMA1", edi: "YES", status: "EDI enabled" },
  { sno: 150, state: "Odisha", zone: "Bhubaneswar", type: "Port", name: "Gopalpur Port", portCode: "INGPR1", edi: "YES", status: "EDI enabled" },
  { sno: 151, state: "Odisha", zone: "Bhubaneswar", type: "ICD", name: "Jharsuguda Icd", portCode: "INJSG6", edi: "YES", status: "EDI enabled" },
  { sno: 152, state: "Odisha", zone: "Bhubaneswar", type: "Port", name: "Paradeep Port Custom House Paradeep Orissa 754142", portCode: "INPRT1", edi: "YES", status: "EDI enabled" },
  { sno: 153, state: "Odisha", zone: "Bhubaneswar", type: "ICD", name: "Icd Kalinganagar,Khurunti,Kic,Jajpur,Odisha 755026", portCode: "INSKD6", edi: "YES", status: "EDI enabled" },
  { sno: 154, state: "Odisha", zone: "Bhubaneswar", type: "ICD", name: "Rail Linked Icd- Jajpur, Odisha", portCode: "INJJK6", edi: "YES", status: "EDI enabled" },
  { sno: 155, state: "Puducherry", zone: "Tiruchirappalli", type: "Port", name: "Mkp Pvt Ltd, Tr Pattinam Post, Karaikal 609606", portCode: "INKRK1", edi: "YES", status: "EDI enabled" },
  { sno: 156, state: "Puducherry", zone: "Tiruchirappalli", type: "Port", name: "Custom House, No. 1 Dumas Street Pondicherry", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 157, state: "Puducherry", zone: "Tiruchirappalli", type: "ICD", name: "Icd Pulichapallam, Pondy Main Road Pondicherry", portCode: "INPNY6", edi: "YES", status: "EDI enabled" },
  { sno: 158, state: "Punjab", zone: "Delhi(P)", type: "Rail", name: "Amritsar Railway Station", portCode: "INASR2", edi: "YES", status: "EDI enabled" },
  { sno: 159, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd Chehertta, Amritsar, Punjab", portCode: "INASR6", edi: "YES", status: "EDI enabled" },
  { sno: 160, state: "Punjab", zone: "Delhi(P)", type: "ACC", name: "Sgrd Jee International Airport, Amritsar", portCode: "INATQ4", edi: "YES", status: "EDI enabled" },
  { sno: 161, state: "Punjab", zone: "Delhi(P)", type: "LCS", name: "Lcs Road Cargo Attari Road Amritsar Punjab", portCode: "INATRB", edi: "YES", status: "EDI enabled" },
  { sno: 162, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd Chawapayal, Ludhiana", portCode: "INCPR6", edi: "YES", status: "EDI enabled" },
  { sno: 163, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd, Pswc, Dhandari Kalan, Ludhiana", portCode: "INDDL6", edi: "YES", status: "EDI enabled" },
  { sno: 164, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd Jalandhar, Dhogri Road Noorpur Jalandhar", portCode: "INJUC6", edi: "YES", status: "EDI enabled" },
  { sno: 165, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd, Ludhiana, Dhandari Kalan Pin-141001", portCode: "INLDH6", edi: "YES", status: "EDI enabled" },
  { sno: 166, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd Gfrl, Ludhiana", portCode: "INSGF6", edi: "YES", status: "EDI enabled" },
  { sno: 167, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Kanesh Icd, Sahnewal, Ludhiana", portCode: "INSNI6", edi: "YES", status: "EDI enabled" },
  { sno: 168, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Adani Icd- Kilaraipur, Dehlon, Ludhiana", portCode: "INQRP6", edi: "YES", status: "EDI enabled" },
  { sno: 169, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd Dappar, Punjab State Warehousing Corporation, Ambala-Chandigarh Highway, Dappar", portCode: "INDPR6", edi: "YES", status: "EDI enabled" },
  { sno: 170, state: "Punjab", zone: "Delhi(P)", type: "ICD", name: "Icd, Kilaraipur, Hind Terminals-Icd, Kilaraipur, Dehlon, Ludhiyana", portCode: "INQRH6", edi: "YES", status: "EDI enabled" },
  { sno: 171, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Concor New Power House Bhagat Ki Kothi Jodhpur", portCode: "INBGK6", edi: "YES", status: "EDI enabled" },
  { sno: 172, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Bhilwara, Sector 5 Azad Nagar Bhilwara", portCode: "INBHL6", edi: "YES", status: "EDI enabled" },
  { sno: 173, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Rajsico Sector 9 Uit Colony Bhiwadi Alwar", portCode: "INBWD6", edi: "YES", status: "EDI enabled" },
  { sno: 174, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Khatuwas, Mandhan Village, Distt, Alwar, Rajasthan", portCode: "INCML6", edi: "YES", status: "EDI enabled" },
  { sno: 175, state: "Rajasthan", zone: "Delhi(P)", type: "ACC", name: "Acc Jaipur, International Airport Sanganer Jaipur", portCode: "INJAI4", edi: "YES", status: "EDI enabled" },
  { sno: 176, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Sanganer Plot No. Sp7 Sia Jaipur Pin - 302020", portCode: "INJAI6", edi: "YES", status: "EDI enabled" },
  { sno: 177, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Rajsico Basni Phase -Ii Jodhpur 342005", portCode: "INJUX6", edi: "YES", status: "EDI enabled" },
  { sno: 178, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd, Concor, Kanakpura, Jaipur Pin -302012", portCode: "INKKU6", edi: "YES", status: "EDI enabled" },
  { sno: 179, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Concor Rawatha Road, Post Mandana Kota", portCode: "INKTT6", edi: "YES", status: "EDI enabled" },
  { sno: 180, state: "Rajasthan", zone: "Delhi(P)", type: "ICD", name: "Icd Thar Dry Port Barmer Road Pal Goan Jodhpur", portCode: "INTHA6", edi: "YES", status: "EDI enabled" },
  { sno: 181, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Arakkonam Maruti Park Netaji Nagar Kainoor-3", portCode: "INAJJ6", edi: "YES", status: "EDI enabled" },
  { sno: 182, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "Port", name: "Cuddalore Port", portCode: "INCDL1", edi: "YES", status: "EDI enabled" },
  { sno: 183, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Chettipalayam, Sf129 Avinashi Taluk Tirupur 52", portCode: "INCHE6", edi: "YES", status: "EDI enabled" },
  { sno: 184, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ACC", name: "Acc Coimbatore, Civil Aerodrome, Coimbatore - 04", portCode: "INCJB4", edi: "YES", status: "EDI enabled" },
  { sno: 185, state: "Tamil Nadu", zone: "Chennai", type: "Port", name: "Ennore Port, Custom House 60 Rajaji Salai Chennai", portCode: "INENR1", edi: "YES", status: "EDI enabled" },
  { sno: 186, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Plot 53, Sipcot Ind. Complex, Phase-1,Hosur 635126", portCode: "INHSU6", edi: "YES", status: "EDI enabled" },
  { sno: 187, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Irugur, Opp Ioc Terminal Irugur Coimbatore -03", portCode: "INIGU6", edi: "YES", status: "EDI enabled" },
  { sno: 188, state: "Tamil Nadu", zone: "Chennai", type: "ICD", name: "Icd Irungattukottai, Sriperumbudur 602105", portCode: "INILP6", edi: "YES", status: "EDI enabled" },
  { sno: 189, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Karur Andan Koil West, Kutkadai Karur Tn", portCode: "INKAR6", edi: "YES", status: "EDI enabled" },
  { sno: 190, state: "Tamil Nadu", zone: "Chennai", type: "Port", name: "Vill.Kattupalli,Tal.Ponneri,Dist.Tiruvellore601 120", portCode: "INKAT1", edi: "YES", status: "EDI enabled" },
  { sno: 191, state: "Tamil Nadu", zone: "Chennai", type: "Port", name: "Custom House 60, Rajaji Salai Chennai 600001", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 192, state: "Tamil Nadu", zone: "Chennai", type: "ACC", name: "Acc, Meenabakkam, Chennai - 600027", portCode: "INMAA4", edi: "YES", status: "EDI enabled" },
  { sno: 193, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Kern Enterprises Private Limited (Kern Icd), Aruppukottai Road, Valayankulam Village,Madurai-625002, Tamil Nadu", portCode: "INMDU6", edi: "YES", status: "EDI enabled" },
  { sno: 194, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "Port", name: "No. 4 First Line Beach Nagapattinam 611001", portCode: "INNPT1", edi: "YES", status: "EDI enabled" },
  { sno: 195, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Singanallur Neelikonnampalayam Coimbatore", portCode: "INSLL6", edi: "YES", status: "EDI enabled" },
  { sno: 196, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Thudialur 2/235C M'Palayam Road Coimbatore 34", portCode: "INTDE6", edi: "YES", status: "EDI enabled" },
  { sno: 197, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Veerapandi, Sf 352 & 353 Palladam Road Tirupur", portCode: "INTHO6", edi: "YES", status: "EDI enabled" },
  { sno: 198, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Tirupur, Raakiyapalayam Avinashi Tirupur 54", portCode: "INTUP6", edi: "YES", status: "EDI enabled" },
  { sno: 199, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "Port", name: "Custom House, Harbour Estate, Tuticorin 628004", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 200, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ICD", name: "Icd Tuticorin, 1663/2B Harbour Exp. Road Tuticorin", portCode: "INTUT6", edi: "YES", status: "EDI enabled" },
  { sno: 201, state: "Tamil Nadu", zone: "Chennai", type: "ICD", name: "M/S Concor,Ennore High Road, Tiruvottiyur, Chennai", portCode: "INTVT6", edi: "YES", status: "EDI enabled" },
  { sno: 202, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ACC", name: "Madurai", portCode: "INIXM4", edi: "YES", status: "EDI enabled" },
  { sno: 203, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "ACC", name: "Tiruchairapalli", portCode: "INTRZ4", edi: "YES", status: "EDI enabled" },
  { sno: 204, state: "Telangana", zone: "Hyderabad", type: "ACC", name: "Acc Shamshabad Airport, Dist:Ranga Reddy Hyderabad", portCode: "INHYD4", edi: "YES", status: "EDI enabled" },
  { sno: 205, state: "Telangana", zone: "Hyderabad", type: "ICD", name: "Icd Hyderabad Andhra Pradesh", portCode: "INSNF6", edi: "YES", status: "EDI enabled" },
  { sno: 206, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Icd Khurja, Arshiya Indiustiyal And Distribution Hub Ltd, Bulandshashr, Up.", portCode: "INAIK6", edi: "YES", status: "EDI enabled" },
  { sno: 207, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Apl Dadri", portCode: "INAPL6", edi: "YES", status: "EDI enabled" },
  { sno: 208, state: "Uttar Pradesh", zone: "Patna", type: "ICD", name: "Icd Agra, East Bank, Motimahal Agra", portCode: "INBLJ6", edi: "YES", status: "EDI enabled" },
  { sno: 209, state: "Uttar Pradesh", zone: "Patna", type: "LCS", name: "Barhni", portCode: "INBNYB", edi: "YES", status: "EDI enabled" },
  { sno: 210, state: "Uttar Pradesh", zone: "Patna", type: "ICD", name: "Icd Chakeri, Gt Road, Kanpur - 208007", portCode: "INCPC6", edi: "YES", status: "EDI enabled" },
  { sno: 211, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Cpl Dadri", portCode: "INCPL6", edi: "YES", status: "EDI enabled" },
  { sno: 212, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Icd Dadri, Gautam Budh Nagar, Up -203207", portCode: "INDER6", edi: "YES", status: "EDI enabled" },
  { sno: 213, state: "Uttar Pradesh", zone: "Patna", type: "ICD", name: "Icd Jry Kanpur, Po:R.K.Nagar Kanpur Pin - 208012", portCode: "INKNU6", edi: "YES", status: "EDI enabled" },
  { sno: 214, state: "Uttar Pradesh", zone: "Patna", type: "ACC", name: "Lucknow", portCode: "INLKO4", edi: "YES", status: "EDI enabled" },
  { sno: 215, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Icd Loni, Loni District Ghaziabad Up", portCode: "INLON6", edi: "YES", status: "EDI enabled" },
  { sno: 216, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Icd Locoshed Moradabad Up", portCode: "INMBD6", edi: "YES", status: "EDI enabled" },
  { sno: 217, state: "Uttar Pradesh", zone: "Patna", type: "ICD", name: "Madho Singh", portCode: "INMBS6", edi: "YES", status: "EDI enabled" },
  { sno: 218, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Modinagar", portCode: "INMUZ6", edi: "YES", status: "EDI enabled" },
  { sno: 219, state: "Uttar Pradesh", zone: "Patna", type: "LCS", name: "Nepalganj Road", portCode: "INNGRB", edi: "YES", status: "EDI enabled" },
  { sno: 220, state: "Uttar Pradesh", zone: "Patna", type: "LCS", name: "Thoothibari, District Maharajganj", portCode: "INNTVB", edi: "YES", status: "EDI enabled" },
  { sno: 221, state: "Uttar Pradesh", zone: "Patna", type: "ICD", name: "Klpl Icd, Panki, Kanpur", portCode: "INPNK6", edi: "YES", status: "EDI enabled" },
  { sno: 222, state: "Uttar Pradesh", zone: "Patna", type: "LCS", name: "Nautanwa (Sonauli)", portCode: "INSNLB", edi: "YES", status: "EDI enabled" },
  { sno: 223, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Star Track Terminal Pvt Ltd Icd Dadri", portCode: "INSTT6", edi: "YES", status: "EDI enabled" },
  { sno: 224, state: "Uttar Pradesh", zone: "Patna", type: "LCS", name: "Tikonia", portCode: "INTKNB", edi: "YES", status: "EDI enabled" },
  { sno: 225, state: "Uttar Pradesh", zone: "Meerut", type: "ICD", name: "Ttp Dadri", portCode: "INTTP6", edi: "YES", status: "EDI enabled" },
  { sno: 226, state: "Uttar Pradesh", zone: "Patna", type: "ACC", name: "Varanasi", portCode: "INVNS4", edi: "YES", status: "EDI enabled" },
  { sno: 227, state: "Uttarakhand", zone: "Patna", type: "LCS", name: "Banbasa", portCode: "INBSAB", edi: "YES", status: "EDI enabled" },
  { sno: 228, state: "Uttarakhand", zone: "Patna", type: "LCS", name: "Dharchula", portCode: "INDLAB", edi: "YES", status: "EDI enabled" },
  { sno: 229, state: "Uttarakhand", zone: "Meerut", type: "ICD", name: "Icd Pantnagar", portCode: "INHDD6", edi: "YES", status: "EDI enabled" },
  { sno: 230, state: "Uttarakhand", zone: "Meerut", type: "ICD", name: "Icd Kashipur, Us Nagar, Uttarakhand", portCode: "INHPI6", edi: "YES", status: "EDI enabled" },
  { sno: 231, state: "Uttarakhand", zone: "Patna", type: "LCS", name: "Jhulaghat (Pithoraghat)", portCode: "INJHOB", edi: "YES", status: "EDI enabled" },
  { sno: 232, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Changrabandha", portCode: "INCBDB", edi: "YES", status: "EDI enabled" },
  { sno: 233, state: "West Bengal", zone: "Kolkata", type: "Port", name: "15/1 Strand Road, Custom House Kolkata 700001", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 234, state: "West Bengal", zone: "Kolkata", type: "ACC", name: "Acc Kolkata, 15/1 Strand Road Custom House Kolkata", portCode: "INCCU4", edi: "YES", status: "EDI enabled" },
  { sno: 235, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Chamurchi", portCode: "INCHMB", edi: "YES", status: "EDI enabled" },
  { sno: 236, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Loksan", portCode: "INCRXB", edi: "YES", status: "EDI enabled" },
  { sno: 237, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Birpara", portCode: "INDLOB", edi: "YES", status: "EDI enabled" },
  { sno: 238, state: "West Bengal", zone: "Kolkata", type: "ICD", name: "Allied Icd Services Ltd Epip Banskopa Durgapur", portCode: "INDUR6", edi: "YES", status: "EDI enabled" },
  { sno: 239, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Fulbari Lcs", portCode: "INFBRB", edi: "YES", status: "EDI enabled" },
  { sno: 240, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Ghojadanga", portCode: "INGJXB", edi: "YES", status: "EDI enabled" },
  { sno: 241, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Hilli", portCode: "INHLIB", edi: "YES", status: "EDI enabled" },
  { sno: 242, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Lcs Jaigaon", portCode: "INJIGB", edi: "YES", status: "EDI enabled" },
  { sno: 243, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Kotawalighat (Mahadipur)", portCode: "INMHDB", edi: "YES", status: "EDI enabled" },
  { sno: 244, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Naxalbari (Panitanki)", portCode: "INPNTB", edi: "YES", status: "EDI enabled" },
  { sno: 245, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "Lcs Petrapole Bongaon West Bengal", portCode: "INPTPB", edi: "YES", status: "EDI enabled" },
  { sno: 246, state: "West Bengal", zone: "Kolkata", type: "Rail", name: "Radhikapur Railway Station", portCode: "INRDP2", edi: "YES", status: "EDI enabled" },
  { sno: 247, state: "West Bengal", zone: "Kolkata", type: "Rail", name: "Ranaghat Railway Station", portCode: "INRNG2", edi: "YES", status: "EDI enabled" },
  { sno: 248, state: "West Bengal", zone: "Kolkata", type: "Rail", name: "Singabad Railway Station", portCode: "INSNG2", edi: "YES", status: "EDI enabled" },
  { sno: 249, state: "West Bengal", zone: "Kolkata", type: "LCS", name: "T.T. Shed (Kidderpore)", portCode: "INTTS1", edi: "YES", status: "EDI enabled" },
  { sno: 250, state: "West Bengal", zone: "Kolkata", type: "Rail", name: "Raiganj Railway Station-Sudarshanpur, West Bengal", portCode: "INRGJ2", edi: "YES", status: "EDI enabled" },
  { sno: 251, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "Aditya CFS Pvt. Ltd.", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 252, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "Container Corprn of India Ltd", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 253, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "Central Warehousing Corporation-I", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 254, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "Central Warehousing Corporation-II", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 255, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "Central Warehousing Corporation- Gandhidham", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 256, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "ASHUTOSH CONTAINER SERVICE PVT LTD", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 257, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "HONEYCOMB LOGISTICS PVT LTD", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 258, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "MUNDRA INTERNATIONAL CONTAINER TERMINAL- CFS", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 259, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "ADANI HAZIRA PORT PVT LTD.", portCode: "INHZA1", edi: "YES", status: "EDI enabled" },
  { sno: 260, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "ARVIND V. JOSHI & COMPANY", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 261, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "HIND MUNDRA TERMINALS PVT LTD MUNDRA", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 262, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "SEABIRD MARINE SERVICES PVT LTD HAZIRA", portCode: "INHZA1", edi: "YES", status: "EDI enabled" },
  { sno: 263, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "CENTRAL WAREHOUSING CORPORATION", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 264, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "FAIRDEAL FREIGHT SOLUTIONS LTD", portCode: "INIXY1", edi: "YES", status: "EDI enabled" },
  { sno: 265, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "CONTRANS LOGISTIC PRIVATE LIMITED", portCode: "INPAV1", edi: "YES", status: "EDI enabled" },
  { sno: 266, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "HIND TERMINAL PRIVATE LIMITED HAZIRA PORT CFS", portCode: "INHZA1", edi: "YES", status: "EDI enabled" },
  { sno: 267, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "LCL LOGISTIX (INDIA) PRIVATE LTD.", portCode: "INPAV1", edi: "YES", status: "EDI enabled" },
  { sno: 268, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "ALL CARGO LOGISTICS LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 269, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "RISHI CONTAINER FREIGHT STATION PVT. LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 270, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "TRANSWORLD TERMINALS PVT. LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 271, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "LANDMARK CFS PVT LTED MUNDRA", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 272, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "EMPEZAR LOGISTICS PVT LTD, MUNDRA PORT", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 273, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "CENTRAL WAREHOUSING CORPORATION", portCode: "INPAV1", edi: "YES", status: "EDI enabled" },
  { sno: 274, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "TG TERMINALS PRIVATE LIMITED", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 275, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "SAURASHTRA FREIGHT PVT. LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 276, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "SEABIRD MARINE SERVICES(GUJARAT) PVT LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 277, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "MUNDHRA CONTAINER FREIGHT STATION PVT. LTD.", portCode: "INMUN1", edi: "YES", status: "EDI enabled" },
  { sno: 278, state: "Gujarat", zone: "Ahmedabad", type: "CFS", name: "NYK AUTO LOGISTICS (INDIA) PVT. LTD.", portCode: "INPAV1", edi: "YES", status: "EDI enabled" },
  { sno: 279, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "ALLCARGO GLOBAL LOGISTICS LIMITED", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 280, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "A.S. SHIPPING AGENCIES PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 281, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "BALMER LAWRIE", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 282, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "BINNY LTD CFS", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 283, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CONTAINER CORPN OF INDIA LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 284, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CONTINENTAL WAREHOUSING CORPN", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 285, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CHANDRA CFS & TERM OPERATORS", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 286, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CWC MADHAVARAM", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 287, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CWC, ROYAPURAM", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 288, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CWC, VIRUGAMBAKKAM", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 289, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CWC, CHROMEPET", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 290, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "DEVADOSS REDDY LOGISTICS PVT. LTD.", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 291, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "ENNORE CARGO CONTAINER TERMINAL", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 292, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "GATEWAY DISTRIPARKS LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 293, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "GERMAN EXPRESS SHPNG AGENC I P", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 294, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "GLOVIS INDIA PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 295, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "KAILASH SHIPPING SERVICES P LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 296, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SICAL DISTRIPARKS LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 297, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SUN GLOBAL LOGISTICS LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 298, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SATTVA HI-TECH & CONWARE P LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 299, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SATTVA CFS AND LOGISTICS PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 300, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SANCO TRANS LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 301, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "TRIWAY CONTAINER FREIGHT STATION", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 302, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "THIRU RANI LOGISTICS PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 303, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "VIKING WAREHOUSING", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 304, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "VISHRUTHA LOGISTICS LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 305, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "O YARD CFS", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 306, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "STP SERVICES PRIVATE LIMITED", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 307, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CALYX CONTAINER TERMINALS PVT. LTD.", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 308, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "NDR INFRASTRUCTURE P LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 309, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "EMPTY CONTAINER YARD - CHENNAI", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 310, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CONTINENTAL WH. CORPORATION (NS) LTD. CHENNAI", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 311, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "EMPTY CONTAINER YARD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 312, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SUDHARSAN LOGISTICS PRIVATE LIMITED", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 313, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "HIND TERMINALS CHENNAI P LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 314, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "APOLLO WORLD CONNECT LTD KATTUPALLI CFS", portCode: "INKAT1", edi: "YES", status: "EDI enabled" },
  { sno: 315, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "INDIAN CORPORATE BUSINESS CENTRE LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 316, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "MARINE INFRASTRUCTURE DEVELOPER PVT. LTD.", portCode: "INKAT1", edi: "YES", status: "EDI enabled" },
  { sno: 317, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "APM TERMINALS INDIA PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 318, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "CENTRAL WAREHOUSING CORPORATION TIRUVOTTIYUR", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 319, state: "Tamil Nadu", zone: "Chennai", type: "CFS", name: "SUPPLY CHAIN LOGISTICS PVT LTD", portCode: "INMAA1", edi: "YES", status: "EDI enabled" },
  { sno: 320, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "A.L. LOGISTICS PVT. LTD", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 321, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "BALMER LAWRIE & CO.LTD", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 322, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "CENTURY PLYBOARDS(I) LTD", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 323, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "CENTRAL WAREHOUSING CORPORATION", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 324, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "CONTAINER CORPORATION OF INDIA LTD.", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 325, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "LCL LOGISTIC (INDIA) PRIVATE LTD.", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 326, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "CENTURY PLYWOODS(I) LTD", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 327, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "RALSON PETROCHEMICALS LTD.", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 328, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "CONTAINER CORP. OF INDIA LTD.", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 329, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "PHONEX LOGISTICS PRIVATE LIMITED", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 330, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "ALLCARGO LOGISTICS LTD KOLKATA PORT", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 331, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "TRANSWORLD TERMINALS PVT. LTD.", portCode: "INCCU1", edi: "YES", status: "EDI enabled" },
  { sno: 332, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "SPEEDY MULTIMODE LTD. CFS", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 333, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "MAHARASHTRA STATE WAREHOUSING CORPORATION", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 334, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "PUNJAB STATE CONTAINER & WAREHOUSING CORP. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 335, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "ALL CARGO LOGISTICS LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 336, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "NAVKAR CORPORATION LTD. II (PREETI LOGISTICS LTD.)", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 337, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "NAVKAR CORPORATION LTD. I (PREETI LOGISTICS LTD.)", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 338, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "NAVKAR CORPORATION LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 339, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "AMEYA LOGISTICS PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 340, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "ASHTE LOGISTICS PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 341, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "APOLLO LOGISOLUTIONS LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 342, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "OCEAN GATE CONTAINER TERMINALS PVT.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 343, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "TRANSINDIA LOGISTICS PARK PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 344, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CWC KALAMBOLI", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 345, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CWC DRONAGIRI NODE", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 346, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CWC LOGISTICS PARK (HIND TERMINAL)", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 347, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CWC IMPEX PARK", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 348, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CWC DISTRIPARK LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 349, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CONTAINER CORPORATION OF INDIA LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 350, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "BALMER & LAWRIE CO. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 351, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "GATEWAY DISTRIPARKS LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 352, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "CONTINENTAL WAREHOUSING (NHAVA SHEVA) LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 353, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "SEABIRD MARINE SERVICES PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 354, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "EFC LOGISTICS PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 355, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "INTERNATIONAL CARGO TERMINAL PRIVATE LIMITED", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 356, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "SBW LOGISTICS PRIVATE LIMITED", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 357, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "KERRYINDEV LOGISTICS PVT LTD", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 358, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "SARVESHWAR LOGISTICS SERVICES PVT LTD NHAVA SHEVA", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 359, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "TAKE CARE LOGISTICS PARK (INDIA) PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 360, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "INTERNATIONAL CARGO TERMINALS & INFRASTRUCTURE PVT", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 361, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "JWC LOGISTICS PARK PVT LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 362, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "JWR LOGISTICS PVT. LTD.", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 363, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "APM TERMINALS INDIA PVT LTD", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 364, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "APM TERMINALS INDIA PVT LTD ANNEX", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 365, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "KESTREL AVIATION PVT LTD", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 366, state: "Maharashtra", zone: "Mumbai, Zone II", type: "CFS", name: "TG TERMINALS PRIVATE LIMITED", portCode: "INNSA1", edi: "YES", status: "EDI enabled" },
  { sno: 367, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "ASIAN TERMINALS", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 368, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "FALCON CFS", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 369, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "CFS PETTA", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 370, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "GATEWAY DISTRIPARKS (KERALA) LTD", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 371, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "M/S COCHIN INTERNATIONAL CONTAINER FREIGHT STATION", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 372, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "M/S COCHIN PORT CONTAINER FREIGHT STATION", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 373, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "CONTAINER CORPORATION OF INDIA COCHIN", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 374, state: "Kerala", zone: "THIRUVANANTHAPURAM", type: "CFS", name: "M/S MIV LOGISTICS PVT. LTD.", portCode: "INCOK1", edi: "YES", status: "EDI enabled" },
  { sno: 375, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "AS shipping CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 376, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Continental CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 377, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "CONCOR CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 378, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Continental W.H (Navaseva) CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 379, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Central Warehousing Corpn.CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 380, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Diamond CFS Park", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 381, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Hari CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 382, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "KSPS Natarajan CFS park", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 383, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Raja Agencies CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 384, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "SEC Container Freight Station", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 385, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "Vilsons CFS", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 386, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "SATTVA HI TECH CONWARE", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 387, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "CONTINENTAL CONTAINER FREIGHT STATION,KARASUR", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 388, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "SICAL DISTRIPARKS LTD", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 389, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "INDEV LOGISTICS PVT LTD KARASOOR PUDUCHERRY", portCode: "INPNY6", edi: "YES", status: "EDI enabled" },
  { sno: 390, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "INDEV LOGISTICS PVT LTD", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 391, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "PONDICHERRY PORT", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 392, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "CHOLA LOGISTIKS PVT LTD", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 393, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "WESTERN GATEWAY CARGO SERVICES PVT. LTD.", portCode: "INAJJ6", edi: "YES", status: "EDI enabled" },
  { sno: 394, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "SATTVA HI TECH CONWARE", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 395, state: "Puducherry", zone: "Tiruchirappalli", type: "CFS", name: "CONTINENTAL CONTAINER FREIGHT STATION", portCode: "INPNY1", edi: "YES", status: "EDI enabled" },
  { sno: 396, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "EMPTY CONTAINER YARD", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 397, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "PROMPT TERMINLAS PVT LTD TUTICORIN", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 398, state: "Tamil Nadu", zone: "Tiruchirappalli", type: "CFS", name: "ALS TUTICORIN TERMINAL PVT LTD TUTICORIN", portCode: "INTUT1", edi: "YES", status: "EDI enabled" },
  { sno: 399, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "Container Corp. of India Ltd", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 400, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "Sravan Shipping Services P Ltd", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 401, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "Central Warehousing Corp.", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 402, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "Gateway East India Pvt Ltd", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 403, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "CONTAINER CORPORATION OF INDIA-MMLP VISAKHAPATNAM", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 404, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "SICAL MULTIMODAL AND RAIL TRANSPORT LTD", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 405, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "GATEWAY DISTRIPARKS LIMITED", portCode: "INKRI1", edi: "YES", status: "EDI enabled" },
  { sno: 406, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "M/S VPL INTEGRAL CFS PVT. LTD.", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 407, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "VISAKHA CONTAINER TERMINAL PVT LTD - CFS", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 408, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "SRAVAN SHIPPING SERVICES PRIVATE LTD CFS - 2", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 409, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "VISAKHA CFS & LOGISTICS PVT LTD, ANAKAPAALI", portCode: "INVTZ1", edi: "YES", status: "EDI enabled" },
  { sno: 410, state: "Andhra Pradesh", zone: "Vishakhapatnam", type: "CFS", name: "SEABIRD DISTRIPARKS (KRISHNAPATNAM) PVT. LTD.", portCode: "INKRI1", edi: "YES", status: "EDI enabled" },
  { sno: 411, state: "West Bengal", zone: "Kolkata", type: "CFS", name: "LCL LOGISTIX (INDIA) PRIVATE LTD.", portCode: "INHAL1", edi: "YES", status: "EDI enabled" },
  { sno: 412, state: "Madhya Pradesh", zone: "Bhopal", type: "CFS", name: "AAI CARGO AURANGABAD AIRPORT", portCode: "INIXU4", edi: "YES", status: "EDI enabled" }
];
